version: "3.9"
services:
  gateway:
    build: gateway
    ports:
      - "8080:3000"
    environment:
      HTTP_PORT: "3000"
      SUPERHEROES_SERVICE_HOST: "superheroes"
      SUPERHEROES_SERVICE_PORT: "5000"
  superheroes:
    build: superheroes
    environment:
      HTTP_PORT: "5000"
    ports:
      - "8081:5000"