name: build-superheroes

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'main'
    paths:
      - 'apps/superheroes/**'

jobs:
  build-push-image:
    uses: ./.github/workflows/build-push-image.yml
    with:
      image_name: superheroes
      build_context: ./apps/superheroes

