name: build-mysql

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'main'
    paths:
      - 'apps/mysql/**'

jobs:
  build-push-image:
    uses: ./.github/workflows/build-push-image.yml
    with:
      image_name: mysql
      build_context: ./apps/mysql

