name: build-customers

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'main'
    paths:
      - 'apps/customers/**'

jobs:
  build-push-image:
    uses: ./.github/workflows/build-push-image.yml
    with:
      image_name: customers
      build_context: ./apps/customers

