name: build-fe

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/frontend_node/**'

jobs:
  build-push-image:
    uses: ./.github/workflows/build-push-image.yml
    with:
      image_name: frontend
      build_context: ./apps/frontend_node

